### PR TITLE
Add utils.js file + new youtube parser

### PR DESCRIPTION
**Pull request by Jackymancs4**
Considering how long what should have been a trivial improvement is taking to be merged I prepared this easy to merge PR that feature:

1. A clean commit history
2. A solid and tested parsing function
3. A commented and readable parsing function

So, in the interest of moving things forward, I suggest @ajayyy to merge this, and close both #80 and #72 .

### CODE REVIEW

**Comment by OfficialNoob** [comment]
My one has more checks :/

**Comment by ajayyy** [comment]
Sorry, if you haven't seen the announcement in discord, I am away from home until Saturday. So, there won't be any merges until then. I've been checking the GitHub notifications a few times per day and just responding to what I've seen quickly

**Comment by ajayyy** [comment]
And please don't take it personally that only one can be merged, it's not a competition :)

**Comment by OfficialNoob** [comment]
@ajayyy well competition "may" result in better code

**Comment by ajayyy** [comment]
Is the /watch/ check required

**Comment by ajayyy** [comment]
I merged #72 and added you as a co-author to my commits.

**Pull request closed without merging**
