### PR TITLE
Use Navigation API when available

### LINKED ISSUE #1328: Improve efficiency
SponsorBlock background currently registers `tabs.onUpdated` listener just to check for URL updates on two domains it is interested in (YouTube and YouTube no-cookie sites). This is an anti-pattern that is known to cause excessive background activations.
https://github.com/ajayyy/SponsorBlock/blob/024480513c7fc02b91eb9a90bad95de4926044ad/src/background.ts#L26

Fortunately, Chrome 102 (which is shipping today) has a much better alternative: [Navigation API](https://chromestatus.com/feature/6232287446302720). This API will actually allow extension to register listener in the content script directly (and avoid background context activation at all.) If you are interested, I can prepare a PR with this change. Also, (on YouTube specifically) older versions of Chrome and current versions of Firefox and Safari can have similar efficiency gains by registering listeners for YouTube-specific DOM events.

If you are interested, I can elaborate and prepare a PR.

### PR DESCRIPTION
**Pull request by bershanskiy**
- [x] I agree to license my contribution under LGPL-3.0 **or** my contribution is from another project with a license compatible with LGPL-3.0

To test this pull request, follow the [instructions in the wiki](https://github.com/ajayyy/SponsorBlock/wiki/Testing-a-Pull-Request).

***

Fixes #1328.

Tested this change on Chrome 102 and Firefox (I do not own any Apple device).

### CODE REVIEW

**Comment by ajayyy** [comment]
Might be a good idea to future proof this by doing the check in the content script, setting a variable in local storage and using that to determine if tabs.onUpdate is needed

**Comment by ajayyy** [comment]
I think 2 is fine, as it doesn't hurt to have two listeners running. So, the first load will have two listeners running, and subsequent page loads will only run one listener.

**Comment by bershanskiy** [comment]
> There is a proxy to local storage already in config.js that can be used. `Config.config.historyApiAvailable`

I'm not sure I follow. Could you elaborate, please? Are you suggesting bundling this technical info together with real user-controlled data?

**Comment by bershanskiy** [comment]
Also, I tested that indeed this patch indeed makes background context more efficient:
 - install both the current release extension and build with this patch
 - look at `chrome://extensions/` and wait until both extension's backgrounds go inactive
 - open a new tab (or navigate somewhere in an old tab or do anything else that would fire `tabs.onUpdated`
 - notice that modified extension's background is still inactive, while release extension's background goes active

**Comment by bershanskiy** [comment]
@ajayyy Should I do anything to advance this PR?

**Pull request merged**
