### PR TITLE
Detect segments on channel trailers

### LINKED ISSUE #58: Support channel trailers

### PR DESCRIPTION
**Pull request by mchangrh**
To test this pull request, follow the [instructions in the wiki](https://github.com/ajayyy/SponsorBlock/wiki/Testing-a-Pull-Request).

***
Excluded
- Info/ Delete/ Upload button

What works/ doesn't
- [x] Submission UI
- [x] Auto Skipping
- [x] Show segments on seek bar
- [x] Skipping Notices
- [x] Skip to Highlight
- [x] Starting/Ending segments
  - [x] Button
  - [x] Keypress
- [x] Extension popout from extensions list
- [x] Manual Skipping via keypress
- [ ] Time with skips removed

closes #58

### CODE REVIEW

**Comment by ajayyy** [comment]
Broken senario:

1. Start on channel page
 - Skips properly
2. Click on video link in current tab
 - No skips load for normal videos

They do appear in the popup, but don't skip and don't have preview bar. Presumably it is attached to the wrong video element.

***

Same issue in reverse (start on video, then go to channel)

**Comment by ajayyy** [comment]
I think I fixed that now

**Comment by mchangrh** [comment]
Have you also tested popping out the trailer to standalone video?

**Comment by ajayyy** [comment]
Yes, seems to work, but clicking back button doesn't draw the preview bar until you click the videos tab, then go back to home. Clicking the channel icon does work, but the back button doesn't emit yt-navigation-finish

**Comment by mchangrh** [comment]
rebased to 3.7, no conflicts or issues

**Comment by mchangrh** [comment]
Only missing feature is time without skips

**Pull request merged**
