### PR TITLE
Change for the v3 manifest

### PR DESCRIPTION
**Pull request by judemont**
- [x] I agree to license my contribution under LGPL-3.0 **or** my contribution is from another project with a license compatible with LGPL-3.0

Hello,

I have modified the current version of the SponsorBlock extension by updating the manifest to support version 3. I made this change because Google has announced that version 2 of the Chrome extension API will no longer be supported starting in March 2023.

I forked the original project and made the necessary changes to the manifest. I also verified that the extension works properly with this new version of the manifest.

I am proposing this pull request so that you can review the changes and integrate them into the original project. If you have any comments or suggestions, please let me know.

Thank you for your attention.

### CODE REVIEW

**Comment by ajayyy** [comment]
FYI there is no date for manifest v3, it is postponed indefinitely https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

**Comment by judemont** [comment]
I apologize for my initial confusion regarding the support for manifest v3. Thank you for letting me know that the migration is postponed indefinitely.

However, I would like to emphasize that even though the migration date is still unknown, it is important to prepare in advance for this transition. Extensions that do not account for the changes introduced by manifest v3 may stop functioning correctly or become unavailable to users in the future.

**Comment by ajayyy** [comment]
But upgrading too early breaks the extension for the many users using older browser versions

**Comment by judemont** [comment]
Okay, no problems.

**Comment by mchangrh** [comment]
just as a reference #165 start talking about mv3

**Pull request closed without merging**
