### PR TITLE
Highlight Button now persists; Implements issue #953

### PR DESCRIPTION
**Pull request by FlorianZahn**
- [x] I agree to license my contribution under LGPL-3.0 **or** my contribution is from another project with a license compatible with LGPL-3.0

To test this pull request, follow the [instructions in the wiki](https://github.com/ajayyy/SponsorBlock/wiki/Testing-a-Pull-Request).

***

This makes Highlight button have the following behavior:
On timeout and skipping: Remove innertext, so that only the symbol remains. Chapters are listed after (they did disappear. I misremembered. Sorry).

I didn't change SkipButtonControlBar.disable(), because i saw it was called somewhere else.
I created a new function and replaced the disable() callse with it.

Reasoning (copied from last time):
This is great for when the highlight-button disappears before you could make the decision if you want to skip. Also you can easily skip to the highligh multiple times, which is pretty reasonable, because it is a highlight. The text disappearing only after a timeout makes sure that new users still know what the button does.

Chrome:
Click: https://www.dropbox.com/s/luvkime4squkv43/ChromeClick.mp4?dl=0
Timeout: https://www.dropbox.com/s/4ll5vbgp2d63140/ChromeTimeout.mp4?dl=0
Firefox:
Click: https://www.dropbox.com/s/sz0v3zngxazera9/FirefoxClick.mp4?dl=0
Timeout: https://www.dropbox.com/s/11xt68qyv3qfpkc/FirefoxTimeout.mp4?dl=0

The issue in question: https://github.com/ajayyy/SponsorBlock/issues/953

### CODE REVIEW

**Comment by FlorianZahn** [comment]
I'm not sure if you like the looks of it, because it sits inbetween the time and the chapertText, but putting it after the chapterText pushed the Highlight button all the way to the right, because the chapterText thing is sooo long

**Comment by FlorianZahn** [comment]
You can press "Enter" mutiple times and it will skip each time

**Comment by ajayyy** [comment]
TODO: Add option to hide this button like other buttons

**Comment by ajayyy** [comment]
Thanks!

**Pull request merged**
