### PR TITLE
Save Map content

### PR DESCRIPTION
**Pull request by OfficialNoob**

### CODE REVIEW

**Comment by ajayyy** [comment]
Why did you remove it from delete?

**Comment by OfficialNoob** [comment]
@ajayyy forgot to add it to the other delete

**Comment by OfficialNoob** [comment]
I dont know what happend to the chrome.sync.remove

**Comment by OfficialNoob** [comment]
I removed deleteProperty as it did not seem to be used for anything
The map can still be deleted with delete SB.config.mapname
And cleared with SB.config.mapname.clear()
Or to remove a key SB.config.mapname.delete(key)

**Pull request merged**
