### PR TITLE
Initial Invidious support

### PR DESCRIPTION
**Pull request by afrmtbl**
Adds initial support for Invidious

Few things to note:
~1. It only works on `invidio.us` and `invidiou.sh` since it's not really possible to detect whether a site is an Invidious instance using just the manifest (as far as I know anyways).~
2. It does not add the buttons to the controls area because there isn't really a good place for them.
3. I only tested on Chromium 78

Addresses #61

### CODE REVIEW

**Comment by ajayyy** [comment]
Oooh, thank you. I really like that for loop, it will be useful if there are anyone sites integrate.

I wanted to setup some [optional permissions](https://stackoverflow.com/a/26677279/1985387) for this to prevent the extension from being disabled on update. Would you be interested in adding that, if not I will :)

Thanks again for this :)

**Comment by afrmtbl** [comment]
I think it'd be better if you implemented it. I'm not too familiar with the codebase yet or `optional_permissions` in general :p

**Comment by TheFrenchGhosty** [comment]
>     1. It only works on `invidio.us` and `invidiou.sh` since it's not really possible to detect whether a site is an Invidious instance using just the manifest (as far as I know anyways).

You can use https://instances.invidio.us/ the same way [Invidition](https://codeberg.org/Booteille/Invidition) uses it.

**Comment by Perflyst** [comment]
If this is not that easily possible maybe an option to set a custom instance would be a workaround for the moment too

**Comment by ajayyy** [comment]
Having it automatic would require more permissions (read ALL sites visited). So, it is probably best not to do that

**Comment by ajayyy** [comment]
Waiting on custom options page

**Comment by ajayyy** [comment]
The notice has a slight visual issue:

Invidious:
image

Normal:
image

**Comment by ajayyy** [comment]
#216

**Comment by ajayyy** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts/register

**Comment by ajayyy** [comment]
This **does not** work in incognito due to [a chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=825507)

**Comment by Perflyst** [comment]
Since you decided to hard-code the invidious instances, I would like to ask you to add `invidious.snopyta.org` too.

**Comment by Caboose700** [comment]
Will there be any way to manually specify a invidious instance? This would be useful for those of us who host their own private invidious that aren't meant to be accessed publicly.

**Comment by ajayyy** [comment]
Yes

**Comment by ajayyy** [comment]
It seems there are somehow even bigger css issues with the notice now.

**Pull request merged**
