### PR TITLE
Popup Styling Upgrades

### PR DESCRIPTION
**Pull request by PickleNik**
- [x] I agree to license my contribution under LGPL-3.0 **or** my contribution is from another project with a license compatible with LGPL-3.0

To test this pull request, follow the [instructions in the wiki](https://github.com/ajayyy/SponsorBlock/wiki/Testing-a-Pull-Request).

***
Screen Shot 2022-05-01 at 10 49 40 PM
Screen Shot 2022-05-01 at 10 50 07 PM

 - improved contrast ratio
 - visual cues to better separate titles from content
 - emphasized project links
 - decreases cumulative layout shifting by swapping username with submissions (username moved)
 - decreases eye strain
 - increases focus & productivity
 - increases money in the bank account (instanteniously)

### CODE REVIEW

**Comment by PickleNik** [comment]
matrix-neo

**Comment by ajayyy** [comment]
Nice! Could you put the logo and name back to the same line to save space? 

I think the close button on the in page popup might interfere with the options button you added (info button on YouTube player). I think it might be better to leave that one in the old place.

**Comment by PickleNik** [comment]
> I think the close button on the in page popup might interfere with the options button you added (info button on YouTube player). I think it might be better to leave that one in the old place.

what's the close button?

**Comment by mchangrh** [comment]
Current interface for comparison

image
image

**Comment by mchangrh** [comment]
> > I think the close button on the in page popup might interfere with the options button you added (info button on YouTube player). I think it might be better to leave that one in the old place.
> 
> what's the close button?

4.2.1
image
4.3
image

**Comment by AlecRust** [comment]
Some thoughts:
- `#111` background feels a bit too dark? Perhaps a very small amount darker is all we need?
- I think "Options" button should remain prominent in the middle. Aside from conflicting with "close" I think it's far less obvious/may be missed.
- Unsure how much benefit increasing the prominence of the footer links brings. I'd be inclined to list them all on one row at the very bottom.
- +1 for swapping Username/Submissions. Personally though I think this whole area is secondary information that should be behind a "Your Work" expander using [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details).

**Comment by PickleNik** [comment]
> - I think "Options" button should remain prominent in the middle. Aside from conflicting with "close" I think it's far less obvious/may be missed.


What if I make it not conflict? 🤔 🙂

**Comment by PickleNik** [comment]
I think it makes sense to have it separate since it takes you to a new tab, unlike other buttons in that row

**Comment by PickleNik** [comment]
Screen Shot 2022-05-02 at 3 17 45 PM
Also, I'd love to 1-line the links, but I'm afraid the translations won't fit

**Comment by PickleNik** [comment]
Screen Shot 2022-05-02 at 3 47 54 PM
Screen Shot 2022-05-02 at 3 48 17 PM
I think this could work, the top row of links is translatable, the bottom row isn't.
Your Work moved to `<details />`

**Comment by ajayyy** [comment]
I don't see the reason to hide the submission count as it appears after the segment list anyway, so isn't taking space away from them

**Comment by PickleNik** [comment]
Screen Shot 2022-05-02 at 9 14 41 PM
after updates:

**Comment by PickleNik** [comment]
> I don't see the reason to hide the submission count as it appears after the segment list anyway, so isn't taking space away from them

So should I remove `Your Work` dropdown? or just take submissions section outside the dropdown?

**Comment by PickleNik** [comment]
https://user-images.githubusercontent.com/31113245/166392146-f3d40951-6712-43e5-889f-27c7212fe740.mov

Settings tooltip is cute :3

**Comment by PickleNik** [comment]
Screen Shot 2022-05-02 at 9 32 00 PM
Expanded `Your Work` looks like this btw

**Comment by AronHK** [comment]
> > * I think "Options" button should remain prominent in the middle. Aside from conflicting with "close" I think it's far less obvious/may be missed.
> 
>  What if I make it not conflict? 🤔 🙂

The rest of the YouTube UI has the close buttons on the right. Same for Windows and the defaults in some of the most popular Linux distros, afaik. I think the extension should be consistent with that.

**Comment by ajayyy** [comment]
thanks!

**Comment by PickleNik** [comment]
> thanks!

I was going to make adjustments for the logo and options that you requested, sorry that I never got around to it lol
thanks for making those for me

**Pull request merged**
