### PR TITLE
Made UUID less predictable

### PR DESCRIPTION
**Pull request by OfficialNoob**

### CODE REVIEW

**Comment by ajayyy** [comment]
Maybe something else can be used as the seed on the non secure browsers. Which are considered not secure?

**Comment by OfficialNoob** [comment]
Well the best way would be to generate it serverside

**Comment by ajayyy** [comment]
Seems to lower security

**Comment by ajayyy** [comment]
User id is a password, it should be decided by the client

**Comment by OfficialNoob** [comment]
Its more like a token then a password because there is "no" user input.
In order to enforce a standard and prevent attacks:
server side generation would be easier and the token can change every x amount of time
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues
I think this is safe as the value is being sent to and validated by the same server anyway

**Comment by OfficialNoob** [comment]
@ajayyy why is this not ready? it should result in the same length value even on older devices

**Comment by ajayyy** [comment]
These aren't in the UUID format yet

**Comment by ajayyy** [comment]
Maybe https://www.uuidgenerator.net/api can be used?

**Comment by OfficialNoob** [comment]
@ajayyy why would you trust uuidgenerator.net and not your own server?

**Comment by OfficialNoob** [comment]
Why are you using a UUID anyway?
"Do not assume that UUIDs are hard to guess"
https://tools.ietf.org/html/rfc4122

**Comment by ajayyy** [comment]
That would just be to make things easier.

**Comment by ajayyy** [comment]
Okay, I see now. That makes sense then, I'll switch to your system then.

**Comment by ajayyy** [comment]
@OfficialNoob Make sure you don't use `var` when you don't have to.

**Pull request merged**
