### PR TITLE
Added Name Attribute to userID Input Field

### PR DESCRIPTION
**Pull request by DrDragonKiller**
Implements #655

### CODE REVIEW

**Comment by ajayyy** [comment]
I'm not sure if it is a good idea to "encourage" this field to be user-created, since it must be randomly generated, as it is not salted.

**Comment by DrDragonKiller** [comment]
when you install the addon the first time it will generate a random id for you. Also the option of changing is collapsed by default.
So I don't think anyone will craft an id by hand (maybe this could be added to the description / it could be salted).

My usecase was, that I want to compare stats and thus change my account sometimes. Currently I always have to copy the long id and paste it there. This PR would allow me to let bitwarden autofill the id in the field whenever I want it to.

**Comment by ajayyy** [comment]
Have you tested if Bitwarden is able to access this page? From a quick search, it doesn't look like extensions can access these pages. 

uBlock does seem to be able to detect the page url, but "block element" isn't working for me.

**Comment by DrDragonKiller** [comment]
you're right. I thought this limitation was only for modifying the page. (Okay technically inpouting stuff also modifies the page but I thought this would work)
I tried setting the name and tried autofill and it didn't work, neither did LastPass recognized any changed fileds. I also tried on the Tamper Monkey Extension Page - No luck there either with both.

Can be closed as it appears to not be possible.

**Comment by ajayyy** [comment]
Thanks for looking into it!

**Pull request closed without merging**
