### PR TITLE
Added config option for excluding skipped content from the video duration

### PR DESCRIPTION
**Pull request by NDevTK**
Config.config.timeWithSkips
Config.config.hideRealTime

### CODE REVIEW

**Comment by ajayyy** [comment]
Looks good, thanks! This just changes the total time right? Not the current time. It might be confusing if the current time is over the total. 

Maybe it would look nice to have the time in brackets? `12:09 (10:20)`. Then, it probably could even be enabled by default.

**Comment by NDevTK** [comment]
@ajayyy it does not affect the current time.
I have added support for stuff like "12:09 (10:20)" when `Config.config.hideRealTime` is false

**Comment by NDevTK** [comment]
@ajayyy any other changes?

**Comment by ajayyy** [comment]
I think switching to using the actual sponsorTimes variable would be nice, but not required. Then the config options need to be added to the options page.

**Pull request merged**
