### PR TITLE
fix: resolve translation template issue

### LINKED ISSUE #447: Translation problem
I've noticed a problem with the translation to german.
image
"Überspringen Unterbrechung?" should be "Unterbrechung überspringen?" but on crowdin I could only find these strings as separate parts so the grammar cannot be fixed in the translation. You would need to update the translation template to include all whole strings and not piece together the translation as it is doing now.

### PR DESCRIPTION
**Pull request by skyfrk**
Hi there! This is my attempt to resolve #447.

### The problem (citing from #447)

> "Überspringen Unterbrechung?" should be "Unterbrechung überspringen?" but on crowdin I could only find these strings as separate parts so the grammar cannot be fixed in the translation. You would need to update the translation template to include all whole strings and not piece together the translation as it is doing now.

### Solution

I updated the default locale translation template with new strings, translated them into German and updated the skip notification popup code to use them. I hope that this is the way to go - I didn't work with crowdin yet 😬.

### Alternative solution

An alternative solution may add locale specific code [here](https://github.com/ajayyy/SponsorBlock/blob/56136d598bc1c960bc50ab09bf21ead903010370/src/components/SkipNoticeComponent.tsx#L80):

```js
if (!this.autoSkip) {
    noticeTitle = chrome.i18n.getMessage("skip") + " " + categoryName + "?";

    if(chrome.i18n.getUILanguage() == "de"){
        noticeTitle = categoryName + " " + chrome.i18n.getMessage("skip").toLowerCase() + "?";
    }
}
```

### CODE REVIEW

**Comment by ajayyy** [comment]
Maybe this would be better with the string being changed to something like "Skip {1}" and then doing String.replace, but then all the translations would have to be updated manually.

**Comment by skyfrk** [comment]
@ajayyy Neat idea! This way there is no redundancy in the translation files. I'll update the PR.

**Comment by skyfrk** [comment]
@ajayyy Ready for review 🎉

**Comment by ajayyy** [comment]
Looks good, thanks!

Before merging, this will have to be fixed in all translations

**Comment by skyfrk** [comment]
@ajayyy Ok, I'll add the strings!

**Comment by ajayyy** [comment]
I think it may be easiest to make a script to do this automatically. I'll try to do this when I have some time.

**Comment by skyfrk** [comment]
@ajayyy I added `skip_category` strings to all languages which have the `skip` string defined. Is this ok?

**Comment by skyfrk** [comment]
@ajayyy what do you think? :D

**Comment by ajayyy** [comment]
Looks good! Did you use a script to do this, or did you do it manually?

**Comment by skyfrk** [comment]
It was manual labor 🙈

**Pull request merged**
