### PR TITLE
allow disabling mute segments locally

### LINKED ISSUE #1343: Allow "disabling" mute segments locally
Mute segments cannot  be hidden in the popup

### PR DESCRIPTION
**Pull request by mchangrh**
- [x] I agree to license my contribution under LGPL-3.0 **or** my contribution is from another project with a license compatible with LGPL-3.0

To test this pull request, follow the [instructions in the wiki](https://github.com/ajayyy/SponsorBlock/wiki/Testing-a-Pull-Request).

***

closes #1343

### CODE REVIEW

**Comment by ajayyy** [comment]
I wonder what the original reasoning was

**Comment by mchangrh** [comment]
My guess is that it was to exclude POI segments?

**Comment by ajayyy** [comment]
seems weird to exclude those too

**Comment by mchangrh** [comment]
let me test it again, I don't think it would be any issue with local disabling

**Pull request merged**
