### PR TITLE
Confirm on video that is not public [TESTING]

### PR DESCRIPTION
**Pull request by OfficialNoob**
# Summary
- Added confirmPrivacy message to en
- Changed videoIDChange to async so that it can now use await
- Added Privacy utils in the content script
- return videoIDChange if user clicks cancel (Does not apply to /embed/)

### CODE REVIEW

**Comment by OfficialNoob** [comment]
isPublic does not work for embedded videos

**Comment by ajayyy** [comment]
Does this appear right away or is it lazy loaded? If so, is a promise needed?

**Comment by ajayyy** [comment]
Maybe add a "always check for sponsors" button to the dialog. Is this possible with vanilla confirmation menus?

**Comment by ajayyy** [comment]
Does this create any noticeable extra delay when pulling sponsors? Also, does this work for the old YouTube theme?

**Comment by OfficialNoob** [comment]
@ajayyy I have tested it for the normal theme :D

**Comment by OfficialNoob** [comment]
Please review the code changes. the UI can be added later just want to warn users currently

**Comment by ajayyy** [comment]
Confirmed to slow sponsor checking. This will have to be optional I guess. Then it can be removed in favour of https://github.com/ajayyy/SponsorBlockServer/issues/25

**Comment by OfficialNoob** [comment]
@ajayyy It is slower now but I dont know how to make it faster without using a hashed substring or a synced local database

**Comment by ajayyy** [comment]
@OfficialNoob yea, there is no way. Hashed substring is the best option.

**Comment by OfficialNoob** [comment]
I think this is done until the new api endpoint is available

**Comment by ajayyy** [comment]
Does this video break it: https://www.youtube.com/watch?v=tO8aJ-TUtJY&list=PL96C35uN7xGJu6skU4TBYrIWxggkZBrF5&index=1 ("Learning playlist")

**Comment by OfficialNoob** [comment]
@ajayyy it did I have now added an exception for that type.
Im not sure if I should use a blacklist or a whitelist for detection

**Comment by OfficialNoob** [comment]
Switched to only alerting on "Private" and "Unlisted"

**Comment by ajayyy** [comment]
It is really only unlisted that is concerning

**Comment by OfficialNoob** [comment]
Will recreate PR due to code changes

**Pull request closed without merging**
