### PR TITLE
 Add a gecko ID to the extension

### PR DESCRIPTION
**Pull request by TheFrenchGhosty**
Some browsers (like GNU Icecat) will mark an add-on as corrupt if the manifest.json doesn't contain a gecko ID.

This PR fixes that.

For more details see: https://github.com/ysard/cookie-quick-manager/issues/75

### CODE REVIEW

**Comment by TheFrenchGhosty** [comment]
I just noticed that a gecko ID is included in https://github.com/ajayyy/SponsorBlock/blob/master/firefox_manifest-extra.json but sadly it isn't working that way and it really needs to be in the manifest.json

**Comment by ajayyy** [comment]
Doesn't the addons store add it automatically. It doesn't work in chrome if added (that's why it is not there)

**Comment by TheFrenchGhosty** [comment]
Sadly no it needs to be added manually into the file... I guess the solution is to do 2 different manifest.json, one for each browser.

**Comment by ajayyy** [comment]
Are you downloading it from the addons store or from the repo?

**Comment by TheFrenchGhosty** [comment]
I tried both, the problem is here for both.

See this gif for the store:

sponsorblock

**Comment by ajayyy** [comment]
This applies to Firefox versions less than 48: https://stackoverflow.com/a/56823677/1985387

**Comment by ajayyy** [comment]
Latest extension now has it

**Comment by TheFrenchGhosty** [comment]
Amazing! It can now be installed, thanks!

**Pull request closed without merging**
